### ISSUE TITLE
Not working with probe cores

### ISSUE THREAD

**Issue by TheShankster** [ValiZockt/SmartDockingAid#1]
The new modes show up when I'm in a pilot controlled vessel but not for any probe cores (tried with "all SAS modes on all probes" switched both on and off)

**Comment by ValentinBischof** [comment]
As of now you will still need a level 3 probe core. The "All SAS modes on all probes" setting is not yet taken into account. (I didn't even knew it existed.) I've already pushed a commit (35ca7ed977f33a46456d120bb278666ae76adaa1) to the master that fixes that, but I haven't made a release yet. If you want to test you can simply download the master branch here from github.

**Comment by TheShankster** [comment]
I only tried doing that to see if it would fix it - never knew that was even a thing before either. I'm having the issue on all probe cores - even SAS level 3 ones (I don't have any other mods currently but ill try with a new install off the ksp site just in case)

**Comment by ValentinBischof** [comment]
> I don't have any other mods currently

If you say only the mode appears if you have high skilled enough pilot not with probe core, is it possible you're missing ModuleManager? Without the Part Module will not be applied to probe cores. (Now added to the forum OP for clarity, wasn't mentioned before). If this not the case, a log would be appreciated.

**Comment by TheShankster** [comment]
Ah yep it seems that was the issue, thanks for the help!
